jobs:
  mvn:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.profile.jdk }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.profile.jdk }}
    - continue-on-error: true
      name: Cache local maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository/

          !~/.m2/repository/org/apache/zookeeper

          '
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Show the first log message
      run: git log -n1
    - continue-on-error: true
      name: Install C Dependencies
      run: 'sudo apt update

        sudo apt install -y libcppunit-dev libsasl2-dev

        '
    - continue-on-error: true
      env:
        MAVEN_OPTS: -Djansi.force=true
      name: Build with Maven (${{ matrix.profile.name }})
      run: mvn -B -V -e -ntp "-Dstyle.color=always" ${{ matrix.profile.args }}
    - continue-on-error: true
      if: ${{ failure() }}
      name: Upload unit test results
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: ignore
        name: surefire-reports-${{ matrix.profile.name }}
        path: ./**/target/surefire-reports/
    - continue-on-error: true
      if: ${{ failure() }}
      name: Upload integration test results
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: ignore
        name: failsafe-reports-${{ matrix.profile.name }}
        path: ./**/target/failsafe-reports/
    strategy:
      fail-fast: false
      matrix:
        profile:
        - args: -Pfull-build apache-rat:check verify -DskipTests spotbugs:check checkstyle:check
          jdk: 8
          name: full-build-jdk8
        - args: -Pfull-build apache-rat:check verify -DskipTests spotbugs:check checkstyle:check
          jdk: 11
          name: full-build-jdk11
        - args: -Pfull-build verify -Dsurefire-forkcount=1 -DskipCppUnit -Dsurefire.rerunFailingTestsCount=5
          jdk: 11
          name: full-build-java-tests
        - args: -Pfull-build verify -Dtest=_ -DfailIfNoTests=false
          jdk: 11
          name: full-build-cppunit-tests
    timeout-minutes: 360
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yaml
