jobs:
  compatibility:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Cache local maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository/

          !~/.m2/repository/org/apache/zookeeper

          '
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Show the first log message
      run: git log -n1
    - continue-on-error: true
      name: Install C Dependencies
      run: 'sudo apt update

        sudo apt install -y libcppunit-dev libsasl2-dev

        '
    - continue-on-error: true
      env:
        MAVEN_OPTS: -Djansi.force=true
      name: Build with Maven
      run: mvn -B -V -e -ntp "-Dstyle.color=always" package -DskipTests
    - continue-on-error: true
      if: matrix.zk != 'nightly'
      name: Download ZooKeeper ${{ matrix.zk }}
      run: 'curl -O https://archive.apache.org/dist/zookeeper/zookeeper-${{ matrix.zk
        }}/apache-zookeeper-${{ matrix.zk }}-bin.tar.gz

        tar -xzvf apache-zookeeper-${{ matrix.zk }}-bin.tar.gz

        '
    - continue-on-error: true
      env:
        ZOOCFG: zoo_sample.cfg
      if: matrix.zk != 'nightly'
      name: Test ZooKeeper nightly server and ${{ matrix.zk }} client
      run: tools/ci/test-connectivity.py --server . --client apache-zookeeper-${{
        matrix.zk }}-bin
    - continue-on-error: true
      env:
        ZOOCFG: zoo_sample.cfg
      if: matrix.zk != 'nightly'
      name: Test ZooKeeper ${{ matrix.zk }} server and nightly client
      run: tools/ci/test-connectivity.py --server apache-zookeeper-${{ matrix.zk }}-bin
        --client .
    - continue-on-error: true
      env:
        ZOOCFG: zoo_sample.cfg
      if: matrix.zk == 'nightly'
      name: Test ZooKeeper nightly server and client
      run: tools/ci/test-connectivity.py --server . --client .
    strategy:
      fail-fast: false
      matrix:
        jdk:
        - 8
        - 11
        zk:
        - 3.5.9
        - 3.6.3
        - 3.7.0
        - nightly
    timeout-minutes: 360
name: End to End Tests
on:
  repository_dispatch:
    types: trigger-ga___e2e.yaml
