jobs:
  mvn:
    name: mvn (triggered by ${{ github.event.sender.login }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.buildRef }}
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Cache local maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository/

          !~/.m2/repository/org/apache/zookeeper

          '
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Show the first log message
      run: git log -n1
    - continue-on-error: true
      name: Install C Dependencies
      run: 'sudo apt update

        sudo apt install -y libcppunit-dev libsasl2-dev

        '
    - continue-on-error: true
      env:
        MAVEN_OPTS: -Djansi.force=true
      name: Build with Maven
      run: mvn -B -V -e -ntp "-Dstyle.color=always" ${{ github.event.inputs.mvnOpts
        }} ${{ github.event.inputs.goals }}
    - continue-on-error: true
      if: ${{ failure() }}
      name: Upload unit test results
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: ignore
        name: surefire-reports
        path: ./**/target/surefire-reports/
    - continue-on-error: true
      if: ${{ failure() }}
      name: Upload integration test results
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: ignore
        name: failsafe-reports
        path: ./**/target/failsafe-reports/
    timeout-minutes: 360
name: Manual Build
on:
  repository_dispatch:
    types: trigger-ga___manual.yaml
